In [1]:
import pandas as pd

df = pd.read_csv("namelist.csv")

df.head()

,namelist_title,namelist_author,namelist_id,an_assault_army,an_clone_army,an_defense_army,an_gene_warrior_army,an_industrial_army,an_machine_assault_1,an_machine_assault_2,...,sn_constructor,sn_exploration_ship,sn_science,sn_transport,sn_headquarters,sn_military_station_large,sn_military_station_medium,sn_military_station_small,sn_ion_cannon,sn_xl_cannon
0,Sci-Fi Novel Mashup (ONL),osiris,novel_mashup,$ORD$ Colonial Assault Unit,$ORD$ Ultra-Marine Commando Force,$ORD$ Colonial Guardian Garrison,$ORD$ Sardaukar Force,$ORD$ Corporate Ultra-Marine Force,$ORD$ Demarchist Assault Army,$ORD$ Demarchist Assault Army,...,Ithaca,Ithaca,Ithaca,Heighliner,United Nations,Ring Station,Plasma Mirror,Sentinel,Graser,Lasgun
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Kepler,Kepler,Kepler,Lighthugger,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Galileo,Galileo,Galileo,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Corona,Corona,Corona,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Ozymandias,Ozymandias,Ozymandias,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
a = "pn_generic_planets sn_corvette	sn_destroyer	sn_frigate	sn_cruiser	sn_battle_cruiser	sn_striker_cruiser	sn_battleship	sn_carrier	sn_dreadnought	sn_titan	sn_flagship	sn_juggernaut	sn_colossus	sn_colonizer	sn_sponsored_colonizer	sn_constructor	sn_exploration_ship	sn_science"
b = a.split()
print(b)

['pn_generic_planets', 'sn_corvette', 'sn_destroyer', 'sn_frigate', 'sn_cruiser', 'sn_battle_cruiser', 'sn_striker_cruiser', 'sn_battleship', 'sn_carrier', 'sn_dreadnought', 'sn_titan', 'sn_flagship', 'sn_juggernaut', 'sn_colossus', 'sn_colonizer', 'sn_sponsored_colonizer', 'sn_constructor', 'sn_exploration_ship', 'sn_science']

In [22]:
names = set()
AO = set("qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM")
for col in b:
    curr_names = df[col].tolist()
    for name in curr_names:
        if type(name) is not str:
            continue
        if set(name).issubset(AO):
            names.add(name.lower())

In [24]:
names.update({"rubicante", "golbez", "biggs", "wedge", "ravana", "morgoth", "finrod", "aznable", "unicorn", "zaku"})
print(names)

{'gamma', 'voltaire', 'biggs', 'centaurus', 'victoria', 'pallas', 'atlas', 'osprey', 'cyclops', 'aquila', 'locust', 'gauntlet', 'valkyrie', 'boadicea', 'pinnace', 'demon', 'conquest', 'indus', 'epsilon', 'monarch', 'hellion', 'ganymede', 'pegasus', 'infinity', 'xiphos', 'bradbury', 'sparrow', 'contender', 'shigure', 'cygnus', 'zodiac', 'empire', 'aldebaran', 'indomitable', 'behemoth', 'altair', 'grizzly', 'carnage', 'direwolf', 'castor', 'liberator', 'yari', 'warpath', 'undaunted', 'donnager', 'finrod', 'kodiak', 'deluge', 'ascendant', 'mir', 'betelgeuse', 'brawler', 'leopard', 'galileo', 'excalibur', 'diadem', 'spector', 'juggernaut', 'cobra', 'ark', 'raptor', 'zeus', 'warlord', 'dauntless', 'centaur', 'asp', 'carrion', 'renown', 'bluejay', 'escalade', 'anubis', 'salamis', 'kraken', 'revolution', 'griffin', 'castellan', 'trumpet', 'punishment', 'caprica', 'beowulf', 'intrepid', 'broadside', 'invader', 'cannon', 'hammer', 'tornado', 'torchbearer', 'zenith', 'tidalwave', 'vortex', 'arbiter', 'lion', 'salamander', 'kaitain', 'astral', 'inferno', 'asgard', 'defiance', 'punisher', 'boreal', 'hellfire', 'borealis', 'alchemax', 'caladan', 'firefly', 'lightning', 'desforge', 'stalwart', 'yggdrasil', 'bastion', 'redemption', 'nomad', 'ozymandias', 'barracuda', 'ahab', 'nightwatch', 'vigilance', 'resurgam', 'warthog', 'cratos', 'morgoth', 'ajax', 'wolfpack', 'wolf', 'nightingale', 'blaze', 'invictus', 'strike', 'corvus', 'templar', 'berserker', 'rook', 'europa', 'mars', 'regent', 'chaser', 'helix', 'meteor', 'citadel', 'renegade', 'uranus', 'avenger', 'upsilon', 'stormbringer', 'dreadnought', 'deathbringer', 'challenger', 'thunderbird', 'aegis', 'onslaught', 'raider', 'cinnabar', 'vanguard', 'ithaca', 'republic', 'bloodthirster', 'agamemnon', 'anvil', 'wildcat', 'concord', 'exodus', 'buccaneer', 'lightbringer', 'cyclone', 'falcon', 'hecate', 'terminus', 'retaliator', 'warlock', 'warspite', 'lorean', 'viper', 'hesperus', 'ardent', 'immortal', 'triumph', 'hela', 'arrowhead', 'blackhawk', 'geneva', 'tauri', 'ix', 'dunkerque', 'eclipse', 'annuminas', 'ravager', 'centauri', 'siren', 'windrider', 'gremlin', 'cannonade', 'thunderhead', 'endeavour', 'blackout', 'jupiter', 'antares', 'shield', 'revenant', 'golbez', 'devastator', 'broadsword', 'dragon', 'castillo', 'knight', 'aries', 'defiant', 'paladin', 'veritas', 'daemon', 'lionheart', 'hydra', 'mustang', 'jaguar', 'bulldozer', 'resolute', 'thunderer', 'xenon', 'dominator', 'nightfall', 'choam', 'zeta', 'honor', 'lucifer', 'specter', 'achilles', 'imperium', 'ghost', 'ararat', 'sabre', 'hornet', 'hurricane', 'supremacy', 'freedom', 'thunderbolt', 'intruder', 'ravana', 'rogue', 'deathstroke', 'barbapiccola', 'condor', 'mercury', 'crusher', 'sirius', 'beholder', 'wedge', 'temeraire', 'alacrity', 'rhea', 'inquisitor', 'unicorn', 'triumphant', 'maverick', 'bulldog', 'heracles', 'fearless', 'hammurabi', 'dominion', 'archangel', 'hydrae', 'stellar', 'nimbus', 'vesta', 'regulus', 'chimera', 'zephyrus', 'odyssey', 'gambit', 'audacious', 'hammerhead', 'blade', 'razorback', 'basilisk', 'albatross', 'spectre', 'zephyr', 'maelstrom', 'relentless', 'justice', 'calamity', 'krait', 'dagger', 'corona', 'lyra', 'yellowstone', 'tachi', 'redoubtable', 'stratosphere', 'wraith', 'imperial', 'deneb', 'itc', 'apollo', 'santiago', 'darkstar', 'striker', 'raven', 'theta', 'thuriya', 'callisto', 'watcher', 'orion', 'fury', 'talon', 'phoenix', 'ophiuchus', 'aviary', 'marauder', 'auriga', 'vindicator', 'butcher', 'shrike', 'helios', 'brigand', 'amalgam', 'decimator', 'grayson', 'fomalhaut', 'saber', 'voyager', 'lancaster', 'desperado', 'abraxas', 'ursa', 'majesty', 'wyvern', 'warrior', 'wolfhound', 'cassiopeia', 'hyperion', 'lac', 'stalker', 'brute', 'mastiff', 'hades', 'sphinx', 'saturn', 'halberd', 'ultimate', 'illustrious', 'hercules', 'quasar', 'bludgeon', 'delta', 'goliath', 'aznable', 'diamondback', 'blitz', 'carrack', 'cerberus', 'havoc', 'harpy', 'deathstalker', 'corsair', 'athena', 'rubicante', 'crusader', 'conqueror', 'centurion', 'earth', 'champion', 'scythe', 'hawkeye', 'harpoon', 'attila', 'seraphim', 'bellerophon', 'aggressor', 'enigma', 'andromeda', 'chariot', 'gemini', 'protector', 'enforcer', 'wolverine', 'widowmaker', 'nova', 'explorer', 'aquarius', 'bullet', 'oblivion', 'warhawk', 'barbarian', 'harrier', 'galahad', 'katana', 'wasp', 'tycho', 'herculean', 'thunder', 'stargazer', 'menkent', 'comet', 'draco', 'longstop', 'copernicus', 'phantom', 'leviathan', 'medusa', 'nike', 'rifter', 'titan', 'acheron', 'canterbury', 'shadow', 'bear', 'bellatrix', 'adjudicator', 'puma', 'flashfire', 'roscinante', 'apocalypse', 'gargoyle', 'venus', 'resurrection', 'nightdancer', 'canopus', 'retribution', 'sovereign', 'kestrel', 'trinity', 'lance', 'titania', 'banshee', 'aerofighter', 'constellation', 'nightshade', 'spitfire', 'starfire', 'invincible', 'unity', 'swift', 'osiris', 'scorpion', 'elysium', 'zaku', 'ceres', 'rocinante', 'triton', 'arrow', 'oberon', 'arcadia', 'gladiator', 'vengeance', 'javelin', 'nemesis', 'ares', 'gorgon', 'guardian', 'bloodhound', 'predator', 'archetype', 'naiad', 'endurance', 'polaris', 'sword', 'starhawk', 'exeter', 'minotaur', 'shark', 'tempest', 'dragonfly', 'hunter', 'arrakis', 'richese', 'breachmaker', 'kepler', 'omega', 'sunburst', 'lancer', 'vega', 'libra', 'lalonde', 'typhoon', 'io', 'pandora', 'caltrop', 'carina', 'daring', 'neptune', 'covenant', 'imperator', 'proxima', 'aurora', 'armageddon', 'harbinger', 'scorpius', 'panther', 'nauvoo', 'whirlwind', 'superlifter', 'spica', 'sls', 'aztec', 'vesuvius', 'colossus', 'void', 'eridanus', 'incubus', 'manticoran', 'ironclad', 'storm', 'epoch', 'sentinel', 'icarus', 'trident', 'sagittarius', 'aviator', 'defender', 'archon', 'annihilator', 'kinetic', 'starfist', 'eros'}

In [27]:
import pickle
print(len(names))
with open("names.pickle", "+wb") as file:
    pickle.dump(list(names), file)

513